CLIENT-GAME: Add system to print sprite and assets of R-Type
X-R-G-B/R-Bus pull request #11
Opened 2023-09-22 14:12 UTC by KitetsuK

MINOR

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-09-22 16:26 UTC, guillaumeAbel requested changes

2023-09-22 16:26 UTC, guillaumeAbel commented on src/Client/Systems/ClientSystems.cpp
> +    for (auto itSprite = arrSprite.begin(); itSprite != arrSprite.end(); itSprite++) {
je pense pas que tu voulais faire ça, là tu render chaque sprite avec chaque rect avec chaque pos

2023-09-22 18:00 UTC, KitetsuK commented on src/Client/Systems/ClientSystems.cpp
> +    for (auto itSprite = arrSprite.begin(); itSprite != arrSprite.end(); itSprite++) {
Je règle ça dès que possible

2023-09-22 20:06 UTC, Saverio976 approved these changes

2023-09-23 22:18 UTC, guillaumeAbel approved these changes

2023-09-23 22:24 UTC, Saverio976 approved these changes

2023-09-23 23:06 UTC, TTENSHII approved these changes

2023-09-23 23:13 UTC, merged