Feature/rb 36 collision system
X-R-G-B/R-Bus pull request #17
Opened 2023-09-23 20:46 UTC by TTENSHII

* **Please check if the PR fulfills these requirements**
- [*] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [* ] Norm of the code has been respected

* **In what state is your pull request?**
- [* ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [*] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-09-23 20:53 UTC, Saverio976 commented on src/Client/Systems/ClientSystems.hpp
> +#include <cstddef>
pourquoi includ e2 fois

2023-09-23 22:31 UTC, guillaumeAbel requested changes

2023-09-23 22:31 UTC, guillaumeAbel commented on src/Client/Systems/ClientSystems.cpp
> +    Registry::components<Types::Position> arrPosition =
change all positions

2023-09-23 22:31 UTC, guillaumeAbel commented on src/ECS/Registry.hpp
> +                    castReturn<Component>().add();
c'est ma faute mais tu peux faire le cast return dans une var avant le for stp

2023-09-24 14:45 UTC, guillaumeAbel approved these changes

2023-09-24 15:36 UTC, Saverio976 approved these changes

2023-09-24 23:18 UTC, Saverio976 approved these changes

2023-09-24 23:19 UTC, merged