Dev -> Main
X-R-G-B/R-Bus pull request #25
Opened 2023-09-27 07:04 UTC by Saverio976

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-09-28 20:22 UTC, TTENSHII approved these changes

2023-09-28 20:38 UTC, KitetsuK commented on docs/contributors.md
> +- [KitetsuK](https://github.com/KitetsuK)
J ai pas d'@ :/

2023-09-28 20:39 UTC, TTENSHII commented on docs/contributors.md
> +- [KitetsuK](https://github.com/KitetsuK)
```suggestion
- [@KitetsuK](https://github.com/KitetsuK)
```

2023-09-29 22:16 UTC, Saverio976 commented on docs/contributors.md
> +- [KitetsuK](https://github.com/KitetsuK)
disoulé

2023-09-29 22:51 UTC, romainpanno approved these changes

2023-09-29 22:51 UTC, romainpanno requested changes
remove comments in formats' scripts .ps1 and .sh

2023-09-29 23:12 UTC, Saverio976 commented
Je corrige le build windows demain

2023-09-30 09:35 UTC, TTENSHII commented on scripts/compil.ps1
> +cmake --build build
```suggestion
cmake --build build
```
```suggestion
cmake --build build -- /m
```

2023-09-30 13:21 UTC, Saverio976 commented
@romainpanno c'est fait

2023-09-30 13:36 UTC, guillaumeAbel approved these changes

2023-09-30 14:23 UTC, romainpanno approved these changes

2023-09-30 14:28 UTC, merged