ECS: Fix, reable systems to auto delete + refactor systemManager + re…
X-R-G-B/R-Bus pull request #31
Opened 2023-09-28 20:05 UTC by guillaumeAbel

…factor Registry custom sparseArrays

MINOR

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-09-28 20:08 UTC, guillaumeAbel commented on src/Client/SceneManager.cpp
> -    Registry::getInstance().addEntity();
this deleted code is some poc, moved in a system for more poc things like proving that system can auto delete after creating player entity.

2023-09-28 20:13 UTC, romainpanno commented on src/Client/SceneManager.cpp
> +#include <iostream>
sys include on top

2023-09-28 20:18 UTC, guillaumeAbel commented on src/Client/SceneManager.cpp
> +#include <iostream>
pas le choix c le formateur qui fait ça quand je les mets dans le bon ordre

2023-09-28 20:28 UTC, TTENSHII commented on src/Client/SceneManager.hpp
> +        Scene getCurrentScene();
Je sais pas si la scene sera modifiée ailleurs mais dans le cas contraire faudrait mettre Scene getCurrentScene() const;

2023-09-28 20:35 UTC, TTENSHII approved these changes

2023-09-28 22:01 UTC, TTENSHII approved these changes

2023-09-29 19:10 UTC, Saverio976 requested changes

2023-09-29 19:10 UTC, Saverio976 commented on src/Client/Systems/Events/EventsSystems.cpp
> +        if (IsKeyDown(KEY_J)) {
Raymib::

2023-09-29 20:02 UTC, guillaumeAbel commented on src/Client/Systems/Events/EventsSystems.cpp
> +        if (IsKeyDown(KEY_J)) {
```suggestion
        if (IsKeyDown(Raylib::KEY_J)) {
```

2023-09-29 22:13 UTC, Saverio976 approved these changes

2023-09-29 22:13 UTC, merged