Feature/rb 54 collision system
X-R-G-B/R-Bus pull request #32
Opened 2023-09-28 20:53 UTC by KitetsuK

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**
Add a collision system between entities
An entity can collide multiple entities
Damage dealing is implemented inside the collision system for now but we re looking forward to move it inside a system

* **Other information**:
New custom types had been created

2023-09-28 21:41 UTC, TTENSHII commented on src/ECS/Systems/Systems.cpp
> +            if (collisionIt->has_value() && positionIt->has_value()) {
sachant que collisionIt++ et positionIt++ sont dans le "if (collisionIt->has_value() && positionIt->has_value())"
Si une entite n'a pas de collision et ou de position ca va boucle inf non ?

2023-09-28 21:51 UTC, KitetsuK commented on src/ECS/Systems/Systems.cpp
> +            if (collisionIt->has_value() && positionIt->has_value()) {
Bien vu je fix ça demain

2023-09-29 09:03 UTC, guillaumeAbel requested changes

2023-09-29 09:03 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +                }
```suggestion
                }
            }
```

2023-09-29 09:03 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +        auto tmpCollisionIt = collisionIt;
collisionIt est deja une copie de l'iterateur passé en parametre vu que c'est pas une ref ou un ptr

2023-09-29 09:03 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +        tmpCollisionIt++;
```suggestion
```

2023-09-29 09:03 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +            if (tmpCollisionIt->has_value() && tmpPositionIt->has_value()) {
```suggestion
            collisionIt++
            positionIt++
            if (tmpCollisionIt->has_value() && tmpPositionIt->has_value()) {
```

2023-09-29 09:03 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +        std::optional<Types::Health> &firstEntityHealth =
code duplicata, call 2 times a function doing the if

2023-09-29 09:06 UTC, guillaumeAbel requested changes

2023-09-29 09:06 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +        if (firstEntityDammage.has_value() && secondEntityHealth.has_value()) {
u dont check infinite health or no dammage

2023-09-29 22:13 UTC, Saverio976 approved these changes

2023-09-30 23:26 UTC, guillaumeAbel approved these changes

2023-09-30 23:26 UTC, merged