Feature/rb 60 layer display gestion
X-R-G-B/R-Bus pull request #34
Opened 2023-09-30 23:43 UTC by guillaumeAbel

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-09-30 23:49 UTC, Saverio976 approved these changes

2023-09-30 23:53 UTC, TTENSHII requested changes

2023-09-30 23:53 UTC, TTENSHII commented on src/Client/Raylib/Graphics/Graphics.cpp
> +        Registry::getInstance().setToDefaultLayer(id);
La classe sprite ne sauvegarde pas l id en attribut, il serait pas mieux de faire "Registry::getInstance().setToDefaultLayer(id)" ailleurs que ici ?

2023-09-30 23:53 UTC, TTENSHII commented on src/Client/Raylib/Graphics/Graphics.hpp
> +                std::size_t id);
same

2023-10-01 10:49 UTC, guillaumeAbel commented on src/Client/Raylib/Graphics/Graphics.cpp
> +        Registry::getInstance().setToDefaultLayer(id);
c'est plus par default si c'est plus set par défault dans le sprite

2023-10-01 11:01 UTC, merged