DOCUMENTATION: Add raylib wrapper documentation
X-R-G-B/R-Bus pull request #35
Opened 2023-10-01 19:22 UTC by TTENSHII

MINOR

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-10-01 19:25 UTC, TTENSHII commented on docs/developer-guide/client/README.md
> +- [**Audio**](audio/index.html): Learn how to add sounds, music, and other audio effects to your game.
I didn't manage to put audio/README.md, it directed me to the wrong thing. I checked the issues on mdbook's github that talked about this but I couldn't solve the problem.

2023-10-02 08:38 UTC, Saverio976 approved these changes

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/README.md
> +- [**Graphics**](graphics/index.html): Learn about advanced graphic rendering, music, animations...
remove this, not needed

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/audio/README.md
> +std::string getPath() const;
put Raylib::Sound:: before all method name

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/audio/README.md
> +## Music Class
Put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/audio/README.md
> +## Sound Class
Put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/events/README.md
> +  Get the last character pressed (unicode).
Raylib:: devant

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/events/README.md
> +  Set the mouse cursor style.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/geometry/README.md
> +  Constructor to create a color with specified `r` (red), `g` (green), `b` (blue), and `a` (alpha) values.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Sprite Class
in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +void unloadSprite();
Raylib::Sprite

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Text Class
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +void setCurrentFontSize(float fontSize);
Raylib::Text

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Image Class
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +void* getData() const;
Raylib::Image::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Shapes and drawing functions
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +void drawRectangle(int posX, int posY, int width, int height, Raylib::Color color);
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Window-related functions
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +  Set a specific window state flag.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +  Get the width of the specified monitor.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +- `void setWindowIcon(Image image);`
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Cursor-related functions
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +  Check if the cursor is within the game window.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Drawing-related functions
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +  End drawing and swap buffers.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Timing-related functions
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +  Get the current time in seconds.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Misc. functions
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +  Take a screenshot and save it to a file with the specified name.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Shapes-related functions
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +- `void drawPixel(int posX, int posY, Raylib::Color color);`
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +  Draw a rectangle at the specified position with the given width, height, and color.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Color/pixel related functions
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +  Create a Color from a hex value.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +## Enum ConfigFlags
put this in another file

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +- `FLAG_VSYNC_HINT`: Enable V-Sync.
Raylib::

2023-10-02 08:38 UTC, Saverio976 commented on docs/developer-guide/client/graphic/README.md
> +
example of usage ?

2023-10-02 08:38 UTC, Saverio976 requested changes
comment

2023-10-02 09:14 UTC, TTENSHII commented on docs/developer-guide/client/graphic/README.md
> +- `FLAG_VSYNC_HINT`: Enable V-Sync.
@Saverio976 c pas dans raylib c dans Raylib::ConfigFlags::

2023-10-02 09:30 UTC, TTENSHII commented
> comment

comment of what

2023-10-02 16:04 UTC, Saverio976 requested changes

2023-10-02 16:04 UTC, Saverio976 commented on docs/developer-guide/client/events/keyboard.md
> +- `bool Raylib::isKeyDown(KeyboardKey key);`
Raylib::

2023-10-02 16:04 UTC, Saverio976 commented on docs/developer-guide/client/events/mouse.md
> +- `bool Raylib::isMouseButtonPressed(MouseButton button);`
Raylib::

2023-10-02 16:04 UTC, Saverio976 commented on docs/developer-guide/client/geometry/constant.md
> +### Color Constants
Et pourquoi pas dans le fichier color ?

2023-10-02 16:04 UTC, Saverio976 commented on docs/developer-guide/client/geometry/vector2.md
> +  Constructor to create a 2D vector with specified `x` and `y` values.
\n

2023-10-02 16:04 UTC, Saverio976 commented on docs/developer-guide/client/geometry/vector4.md
> +## Vector4 Structure
Diff between vector4 et rectangle

2023-10-02 16:04 UTC, Saverio976 commented on docs/developer-guide/client/graphic/colorsPixels.md
> +- `Raylib::Color Raylib::colorFromNormalized(Vector4 normalized);`
Raylib::

2023-10-02 16:04 UTC, Saverio976 commented on docs/developer-guide/client/graphic/configFlags.md
> +```
How to enable full screen and vsync at same time example. ?

2023-10-02 16:10 UTC, TTENSHII commented on docs/developer-guide/client/graphic/configFlags.md
> +```
its not a "how to code in cpp doc" its a raylib wrapper doc

2023-10-02 16:27 UTC, TTENSHII commented on docs/developer-guide/client/geometry/vector4.md
> +## Vector4 Structure
It's a raylib wrapper so it takes its functionalities.
For more information, see the rectangle struct (l.244) and the Vector4 struct(l.217) in the original raylib.h file at https://github.com/raysan5/raylib/blob/master/src/raylib.h.
The Vector4 struct represents a vector with four components (x, y, z, w), while the Rectangle struct represents a rectangle with position and size properties (x, y, width, height) in 2D.

For more more more informations about geometry:
https://en.wikipedia.org/wiki/Rectangle
https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/vector4/

2023-10-02 19:42 UTC, Saverio976 approved these changes

2023-10-02 19:42 UTC, merged