Feature/rb 56 check deads
X-R-G-B/R-Bus pull request #38
Opened 2023-10-02 18:21 UTC by TTENSHII

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-10-02 18:45 UTC, KitetsuK approved these changes

2023-10-02 19:04 UTC, guillaumeAbel requested changes

2023-10-02 19:04 UTC, guillaumeAbel commented on src/Client/Systems/Graphic/DeathSystems.cpp
> +        std::cout << "Player " << id << " is dead" << std::endl;
set animRect to dead rect

2023-10-02 19:04 UTC, guillaumeAbel commented on src/Client/Systems/Graphic/DeathSystems.cpp
> +        try {
should iterate over a vector of type_index

2023-10-02 19:04 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +                arrDead[*itIds].deathFunction
call static function

2023-10-03 19:09 UTC, Saverio976 requested changes

2023-10-03 19:09 UTC, Saverio976 commented on src/Client/SceneManager.cpp
> +constexpr int screenWidth  = 800;
Huh ?

2023-10-03 19:09 UTC, Saverio976 commented on CMakeLists.txt
> -endif()
Pourquoi ?

2023-10-03 20:56 UTC, guillaumeAbel approved these changes

2023-10-03 21:15 UTC, Saverio976 approved these changes

2023-10-03 21:15 UTC, Saverio976 commented on src/ECS/ECSCustomTypes.hpp
> -// all values are in percentage of the screen
Pourquoi supprimer ?

2023-10-03 21:16 UTC, merged