ECS/CLIENT-GAME Add debug mode for collision rect
X-R-G-B/R-Bus pull request #39
Opened 2023-10-02 18:38 UTC by KitetsuK

Add player shoot
MINOR

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**
Add debug mode for collision rectangle
Add player shoot

* **Other information**:

2023-10-02 19:08 UTC, TTENSHII requested changes

2023-10-02 19:08 UTC, kw4ntiq commented on src/ECS/ECSCustomTypes.hpp
> +            // maybe enum better ?
Yep

2023-10-02 19:08 UTC, TTENSHII commented on src/Client/Systems/Events/EventsSystems.cpp
> +                if (arrPosition.exist(id) && arrRect.exist(id)) {
oh le if for if

2023-10-02 19:08 UTC, TTENSHII commented on src/Client/Systems/Events/EventsSystems.hpp
> +        void shootBullet(std::size_t, std::size_t);
```suggestion
        void shootBullet(std::size_t /*unused*/, std::size_t /*unused*/);
```

2023-10-02 19:08 UTC, TTENSHII commented on src/ECS/Systems/Systems.cpp
>      void init(std::size_t managerId, std::size_t systemId)
ca serait bien de remettre les trucs de dev genre le player qui court et tout

2023-10-02 19:19 UTC, guillaumeAbel requested changes

2023-10-02 19:19 UTC, guillaumeAbel commented on src/Client/Systems/Events/EventsSystems.cpp
> +                }
🤮

2023-10-02 19:19 UTC, guillaumeAbel commented on src/ECS/ECSCustomTypes.hpp
> +            // maybe enum better ?
yes yes yes

2023-10-02 19:19 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +                         arrCollisionRect[id].height + 2});
why don't fit exactly the collisionRect

2023-10-02 19:52 UTC, Saverio976 commented on src/Client/Systems/Events/EventsSystems.cpp
> +                }
C'est quoi ça

2023-10-03 11:31 UTC, guillaumeAbel approved these changes

2023-10-03 17:04 UTC, guillaumeAbel requested changes
Debug mode is launched by default

2023-10-04 15:23 UTC, Saverio976 approved these changes

2023-10-04 15:23 UTC, guillaumeAbel approved these changes

2023-10-04 15:25 UTC, TTENSHII approved these changes

2023-10-04 15:38 UTC, merged