Feature/rb 22 network
X-R-G-B/R-Bus pull request #43
Opened 2023-10-03 21:34 UTC by romainpanno

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-10-03 22:01 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +        //            handlePacketIdsReceived(*header);
pourquoi comment ?

2023-10-03 22:17 UTC, Saverio976 approved these changes

2023-10-04 08:08 UTC, guillaumeAbel requested changes

2023-10-04 08:08 UTC, guillaumeAbel commented on src/Nitwork/ANitwork.cpp
> +
```suggestion
static void callReceiveHandler(std::string message)
{
    std::cerr << message << std::endl;
    startReceiveHandler();
}

```
To avoid some spaces to the below function

2023-10-04 08:08 UTC, guillaumeAbel commented on src/Nitwork/ANitwork.cpp
> +                }
static function

2023-10-04 08:08 UTC, guillaumeAbel commented on src/Nitwork/ANitwork.cpp
> +                    }
static function

2023-10-04 20:54 UTC, Saverio976 requested changes

2023-10-04 20:54 UTC, Saverio976 commented on CMakeLists.txt
> +            VS_GLOBAL_RunCodeAnalysis "<$<CONFIG:Debug>:Debug>"
J'ai fait de la merde ici

2023-10-04 20:54 UTC, Saverio976 commented on CMakeLists.txt
> +            VS_GLOBAL_EnableClangTidyCodeAnalysis "<$<:Debug>:Debug>"
J'ai fait de la merde ici

2023-10-04 20:54 UTC, Saverio976 commented on CMakeLists.txt
> +            VS_GLOBAL_RunCodeAnalysis "<$<CONFIG:Debug>:Debug>"
Il faut juste mettre ce qu'il y avait avant

2023-10-05 13:34 UTC, guillaumeAbel approved these changes

2023-10-05 14:48 UTC, guillaumeAbel approved these changes

2023-10-05 15:03 UTC, merged