Feature/rb 59 parallax system
X-R-G-B/R-Bus pull request #48
Opened 2023-10-04 20:04 UTC by KitetsuK

PATCH

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-10-05 13:35 UTC, guillaumeAbel commented on assets/Json/parallaxData.json
> +}
EOF

2023-10-05 13:43 UTC, guillaumeAbel requested changes

2023-10-05 13:43 UTC, guillaumeAbel commented on assets/Json/parallaxData.json
> +}
EOF

2023-10-05 13:43 UTC, guillaumeAbel commented on assets/Json/playerData.json
> +}
EOF

2023-10-05 13:43 UTC, guillaumeAbel commented on deps/json/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME_SERVER} PRIVATE nlohmann_json::nlohmann_json)
EOF

2023-10-05 17:41 UTC, Saverio976 requested changes

2023-10-05 17:41 UTC, Saverio976 commented on src/ECS/Systems/Managers/SystemManager.cpp
> +#include <iostream>
iostream ? Logger existe

2023-10-05 17:41 UTC, Saverio976 commented on src/ECS/Systems/Managers/SystemManager.hpp
> +
pourquoi un espace ?

2023-10-05 17:41 UTC, Saverio976 commented on src/ECS/Systems/Systems.cpp
> +        std::cout << "Could not load the json data : An error occured." << std::endl;
???? Logger

2023-10-05 17:41 UTC, Saverio976 commented on src/ECS/Systems/Systems.cpp
> +        nlohmann::json jsonData = openJsonData("assets/Json/parallaxData.json");
const string

2023-10-05 19:43 UTC, guillaumeAbel requested changes

2023-10-05 19:43 UTC, guillaumeAbel commented on src/ECS/Systems/Systems.cpp
> +#include <iostream>
iostream

2023-10-06 12:53 UTC, guillaumeAbel approved these changes

2023-10-06 14:12 UTC, merged