Feature/rb 67
X-R-G-B/R-Bus pull request #62
Opened 2023-10-09 18:06 UTC by Saverio976

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-10-09 18:20 UTC, TTENSHII approved these changes

2023-10-10 15:19 UTC, romainpanno requested changes

2023-10-10 15:19 UTC, romainpanno commented on src/Client/Systems/Graphic/DeathSystems.cpp
> +                    std::cout << "set fct " << std::endl;
remove cout

2023-10-10 15:19 UTC, romainpanno commented on src/Client/Systems/Graphic/DeathSystems.cpp
> +#include <iostream>
remove include

2023-10-10 15:19 UTC, romainpanno commented on src/ECS/Systems/Systems.cpp
> +#include <iostream>
remove

2023-10-10 15:19 UTC, romainpanno commented on src/ECS/Systems/Systems.cpp
> +            std::cout << "yes" << std::endl;
yes yes yes, remove plz cout in this func

2023-10-10 19:04 UTC, romainpanno approved these changes

2023-10-10 19:17 UTC, merged