Feature/rb 82 respond to client enemy death
X-R-G-B/R-Bus pull request #66
Opened 2023-10-10 11:19 UTC by romainpanno

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-10-10 11:43 UTC, TTENSHII approved these changes

2023-10-10 11:50 UTC, TTENSHII requested changes
Just fix windows compilation

2023-10-10 13:17 UTC, Saverio976 requested changes

2023-10-10 13:17 UTC, Saverio976 commented on src/Client/Systems/Network/ClientNetwork.cpp
> +    static bool getPlayerId(std::size_t &id)
set

2023-10-10 21:41 UTC, romainpanno commented on src/ECS/Systems/Systems.cpp
> +    static void sendEnemyDeath(std::size_t id)
warning here because send enemy death from client is not already implemented, it lead to an unused value ('id') only on client compilation

2023-10-11 08:48 UTC, guillaumeAbel approved these changes

2023-10-11 08:52 UTC, Saverio976 requested changes

2023-10-11 08:52 UTC, Saverio976 commented on src/ECS/ECSCustomTypes.hpp
>              static unsigned int _enemyNb;
mutex pour y acceder

2023-10-11 09:01 UTC, Saverio976 approved these changes

2023-10-11 09:06 UTC, TTENSHII approved these changes

2023-10-11 09:11 UTC, merged