Dev to main
X-R-G-B/R-Bus pull request #72
Opened 2023-10-11 09:12 UTC by TTENSHII

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [ ] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [ ] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-10-11 09:56 UTC, KitetsuK approved these changes

2023-10-11 09:59 UTC, Saverio976 approved these changes

2023-10-11 17:35 UTC, romainpanno approved these changes

2023-10-11 19:28 UTC, guillaumeAbel approved these changes

2023-10-11 19:28 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +            std::cerr << "Error: context threads failed" << std::endl;
logger

2023-10-11 19:29 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +            std::cerr << "Error: clock thread failed" << std::endl;
logger

2023-10-11 19:34 UTC, Saverio976 requested changes, later dismissed

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +            callReceiveHandler("Error: " + error.message());
```suggestion
            callReceiveHandler("NITWORK: " + error.message());
```

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +            callReceiveHandler("Error: header not received");
```suggestion
            callReceiveHandler("NITWORK: header not received");
```

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +            callReceiveHandler("Error: header magick not valid");
```suggestion
            callReceiveHandler("NITWORK: header magick not valid");
```

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +            callReceiveHandler("Error: header nb action not valid or already received");
```suggestion
            callReceiveHandler("NITWORK: header nb action not valid or already received");
```

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +                    std::cerr << "Error: packet not found" << std::endl;
logger

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +                std::cerr << e.what() << std::endl;
logger

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +                std::cerr << "Error: action not found" << std::endl;
logger

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/ANitwork.cpp
> +                std::cerr << e.what() << std::endl;
logger

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/NitworkClient.cpp
> +            std::cerr << "Error: endpoint is not the server" << std::endl;
logger

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/NitworkClient.cpp
> +            std::cerr << "Error: action not found" << std::endl;
logger

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/NitworkClient.cpp
> +        Logger::info(
```suggestion
        Logger::debug(
```

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/NitworkClient.cpp
> +            std::cerr << "Error: magick is not START_GAME" << std::endl;
logger

2023-10-11 19:34 UTC, Saverio976 commented on src/Nitwork/NitworkClient.cpp
> +        std::cout << "Game started" << std::endl;
logger

2023-10-12 08:16 UTC, guillaumeAbel requested changes

2023-10-12 08:16 UTC, guillaumeAbel commented on src/Nitwork/NitworkServer.cpp
> +        std::cout << "Send PLAYER_INIT to " << endpoint.address().to_string() << ":" << endpoint.port()
cout

2023-10-12 08:16 UTC, guillaumeAbel commented on src/Nitwork/ANitwork.hpp
> +                std::cout << "updatedPacket.header.ids_received: " << data.header.ids_received << std::endl;
cout

2023-10-12 08:16 UTC, guillaumeAbel commented on src/Nitwork/NitworkServer.cpp
> +        std::cout << "Send START_GAME to " << endpoint.address().to_string() << ":" << endpoint.port()
cout

2023-10-12 08:55 UTC, guillaumeAbel approved these changes

2023-10-12 09:29 UTC, romainpanno approved these changes

2023-10-12 09:29 UTC, merged