CLIENT-NETWORK: Add receive enemy nb
X-R-G-B/R-Bus pull request #74
Opened 2023-10-11 15:59 UTC by guillaumeAbel

MINOR

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] Norm of the code has been respected

* **In what state is your pull request?**
- [ ] Ready to merge / Waiting a reviwer to see my work.
- [x] Work In Progress (WIP) / My work is not finish but i want daily reviews. (Draft)
- [ ] CI Review / I want to see what the CI thinks of my work.
- [ ] Need feedback / Just to have feedback on what i produced. (May not be merged)

* **What kind of change does this PR introduce?** (You can choose multiple)
- [ ] Bug fix
- [x] Feature request
- [ ] New / Updated documentation
- [ ] Testing CI ( Make the pull request in draft mode)

* **What is the current behavior?** (link an issue based on the kind of change this pr introduce)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2023-10-11 16:16 UTC, Saverio976 approved these changes

2023-10-12 08:31 UTC, romainpanno requested changes

2023-10-12 08:31 UTC, romainpanno commented on src/Nitwork/ANitwork.hpp
>                  {START_GAME,
Rename enum to START_WAVE

2023-10-12 08:31 UTC, romainpanno commented on src/Nitwork/Nitwork.h
>      START_GAME = 3,
START_WAVE

2023-10-12 09:41 UTC, romainpanno approved these changes

2023-10-12 09:51 UTC, merged